/* eslint-disable react-hooks/rules-of-hooks */
import { CustomConnect } from "components/ConnectWallet";
import type { NextPage } from "next";
import Head from "next/head";

const lp: NextPage = () => {
    return (
        <div>
            <Head>
                <title>KibuOnBase</title>
                <meta name="description" content="Generated by create next wagmi dapp" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div
                style={{
                    display: "flex",
                    justifyContent: "center",   // Horizontally center the content
                    alignItems: "center",        // Vertically center the content
                    height: "100vh",             // Full viewport height
                    flexDirection: "column",     // Align items in a column
                    backgroundImage: "url('/uni-bg.jpg')",  // Background image URL
                    backgroundSize: "cover",     // Ensure the image covers the whole page
                    backgroundPosition: "center",// Center the background image
                    backgroundRepeat: "no-repeat",// Prevent image from repeating
                }}
            >
                <CustomConnect />
            </div>
        </div>
    );
};

export default lp;
