/* eslint-disable react-hooks/rules-of-hooks */
import { CustomConnect } from "components/ConnectWallet";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const lp: NextPage = () => {
    const router = useRouter();  // Initialize the Next.js router

    const handleRedirect = () => {
        router.push('/home');  // Redirect to the home page
    };

    return (
        <div>
            <Head>
                <title>Create Wagmi Example Dapp</title>
                <meta name="description" content="Generated by create next wagmi dapp" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div
                style={{
                    display: "flex",
                    justifyContent: "center",   // Horizontally center the content
                    alignItems: "center",        // Vertically center the content
                    height: "100vh",             // Full viewport height
                    flexDirection: "column",     // Align items in a column
                }}
            >
                <CustomConnect />
                <div style={{ marginTop: "20px" }}>  {/* Add some spacing between the elements */}
                    <button
                        onClick={handleRedirect}
                        style={{
                            backgroundColor: "#007bff",  // Button styling
                            color: "#fff",
                            border: "none",
                            padding: "10px 20px",
                            borderRadius: "8px",
                            fontSize: "16px",
                            cursor: "pointer",
                            transition: "background-color 0.3s",
                        }}
                        onMouseEnter={(e) => e.currentTarget.style.backgroundColor = "#0056b3"}
                        onMouseLeave={(e) => e.currentTarget.style.backgroundColor = "#007bff"}
                    >
                        Go to Home
                    </button>
                </div>
            </div>
        </div>
    );
};

export default lp;
