/* eslint-disable react-hooks/rules-of-hooks */
import MemecoinStory from "components/pages";
import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const story: NextPage = () => {
    const router = useRouter();  // Initialize the Next.js router

    const handleRedirect = () => {
        router.push('/home');  // Redirect to the home page
    };

    return (
        <div>
            <Head>
                <title>Create Wagmi Example Dapp</title>
                <meta name="description" content="Generated by create next wagmi dapp" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div
                style={{
                    display: "flex",
                    justifyContent: "center",   // Horizontally center the content
                    alignItems: "center",        // Vertically center the content
                    flexDirection: "column",     // Align items in a column
                }}
            >
                <MemecoinStory />
            </div>
        </div>
    );
};

export default story;
